import { useEffect, useState } from "react";
import { useAuthStore } from "../../../store/auth.store";
const API=(import.meta.env.VITE_API_URL||"http://localhost:5000/api").replace(/\/$/,"");
type U={_id:string;name:string;email:string;role:"ADMIN"|"CUSTOMER"|"RIDER";isActive:boolean};
export function UserManagement(){const token=useAuthStore(s=>s.token);const [users,setUsers]=useState<U[]>([]);const [error,setError]=useState("");
async function load(){try{const r=await fetch(`${API}/platform/users`,{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();if(!r.ok)throw new Error(j.message);setUsers(j.users||[])}catch(e:any){setError(e.message||"Unable to load users")}}
useEffect(()=>{load()},[token]);
async function update(id:string,patch:Partial<U>){const r=await fetch(`${API}/platform/users/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(patch)});if(r.ok)load();else{const j=await r.json();setError(j.message||"Update failed")}}
return <div className="space-y-6"><div><h1 className="text-3xl font-black text-brand-blue">Users & Roles</h1><p className="mt-1 text-slate-500">Manage customer, rider and administrator access.</p></div>{error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}<div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50"><tr><th className="p-4">#</th><th className="p-4">Name</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Status</th></tr></thead><tbody>{users.map((u,i)=><tr className="border-t" key={u._id}><td className="p-4">{i+1}</td><td className="p-4 font-semibold">{u.name}</td><td className="p-4">{u.email}</td><td className="p-4"><select className="rounded-lg border p-2" value={u.role} onChange={e=>update(u._id,{role:e.target.value as U["role"]})}><option>ADMIN</option><option>CUSTOMER</option><option>RIDER</option></select></td><td className="p-4"><button className={u.isActive?"text-green-700":"text-red-600"} onClick={()=>update(u._id,{isActive:!u.isActive})}>{u.isActive?"Active":"Disabled"}</button></td></tr>)}</tbody></table></div></div></div>}
