import {Routes,Route,Link,Navigate} from "react-router-dom";
import {PublicLayout} from "./layouts/PublicLayout";
import {AppLayout} from "./layouts/AppLayout";
import {ProtectedRoute} from "./app/ProtectedRoute";
import {Login} from "./modules/auth/pages/Login";
import {Register} from "./modules/auth/pages/Register";
import {AdminDashboard} from "./modules/admin/pages/Dashboard";
import {CustomerDashboard} from "./modules/customer/pages/Dashboard";
import {BookPickup} from "./modules/customer/pages/BookPickup";
import {CustomerPickups} from "./modules/customer/pages/Pickups";
import {RiderDashboard} from "./modules/rider/pages/Dashboard";
import {RiderPickups} from "./modules/rider/pages/Pickups";
import {FeaturePage} from "./modules/platform/pages/FeaturePage";
import {UserManagement} from "./modules/platform/pages/UserManagement";

function Home(){return <><section className="bg-gradient-to-br from-brand-blue to-brand-blue-light px-6 py-24 text-white"><div className="mx-auto max-w-7xl"><p className="font-bold text-orange-200">SMART PICKUP MANAGEMENT</p><h1 className="mt-4 max-w-3xl text-5xl font-black">Book, manage and track pickups from one platform.</h1><p className="mt-6 max-w-2xl text-lg text-white/80">A scalable platform for customers, dispatch teams and riders.</p><Link to="/register" className="btn-primary mt-8">Start Booking</Link></div></section><section className="mx-auto grid max-w-7xl gap-6 px-6 py-16 md:grid-cols-3">{["Easy Booking","Smart Dispatch","Complete History"].map(x=><div className="card p-7" key={x}><h3 className="text-xl font-bold text-brand-blue">{x}</h3><p className="mt-2 text-slate-500">Role-based pickup management for your business.</p></div>)}</section></>}
const F=({resource,title,description}:{resource:string;title:string;description:string})=><FeaturePage resource={resource} title={title} description={description}/>;

export default function App(){return <Routes>
 <Route element={<PublicLayout/>}><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/></Route>
 <Route element={<ProtectedRoute roles={["ADMIN"]}/>}><Route element={<AppLayout/>}>
  <Route path="/admin/dashboard" element={<AdminDashboard/>}/><Route path="/admin/customers" element={<F resource="profiles" title="Customers" description="Manage customer accounts and profiles."/>}/><Route path="/admin/riders" element={<F resource="profiles" title="Riders" description="Manage rider profiles and operational records."/>}/><Route path="/admin/pickup-plans" element={<F resource="pickup-plans" title="Pickup Plans" description="Create and manage pickup plans."/>}/><Route path="/admin/pickups" element={<F resource="pickups" title="Orders / Pickups" description="Manage all pickup orders and statuses."/>}/><Route path="/admin/carriers" element={<F resource="carriers" title="Carriers" description="Manage carriers used for pickups."/>}/><Route path="/admin/coverage-areas" element={<F resource="coverage-areas" title="Coverage Areas" description="Manage service coverage areas."/>}/><Route path="/admin/addon-services" element={<F resource="addon-services" title="Add-on Services" description="Manage optional pickup services."/>}/><Route path="/admin/pricing" element={<F resource="pricing" title="Pricing" description="Manage pricing rules and charges."/>}/><Route path="/admin/payments" element={<F resource="payments" title="Payments" description="Monitor and manage payments."/>}/><Route path="/admin/notifications" element={<F resource="notifications" title="Notifications" description="Manage system notifications."/>}/><Route path="/admin/reports" element={<F resource="reports" title="Reports" description="Review operational reports."/>}/><Route path="/admin/settings" element={<F resource="settings" title="Settings" description="Manage platform settings."/>}/><Route path="/admin/users" element={<UserManagement/>}/><Route path="/admin/audit-logs" element={<F resource="audit-logs" title="Audit Logs" description="Review platform activity and audit records."/>}/>
 </Route></Route>
 <Route element={<ProtectedRoute roles={["CUSTOMER"]}/>}><Route element={<AppLayout/>}>
  <Route path="/customer/dashboard" element={<CustomerDashboard/>}/><Route path="/customer/profile" element={<F resource="profiles" title="Profile" description="Manage your customer profile."/>}/><Route path="/customer/business" element={<F resource="profiles" title="Business Details" description="Manage your business details."/>}/><Route path="/customer/addresses" element={<F resource="addresses" title="Addresses" description="Manage pickup and delivery addresses."/>}/><Route path="/customer/book-pickup" element={<BookPickup/>}/><Route path="/customer/pickups" element={<CustomerPickups/>}/><Route path="/customer/upcoming" element={<F resource="pickups" title="Upcoming Pickups" description="View your upcoming pickup bookings."/>}/><Route path="/customer/pickup-details" element={<F resource="pickups" title="Pickup Details" description="View pickup details and status."/>}/><Route path="/customer/payments" element={<F resource="payment-methods" title="Payment Methods" description="Manage your payment methods."/>}/><Route path="/customer/invoices" element={<F resource="invoices" title="Invoices" description="View your pickup invoices."/>}/><Route path="/customer/notifications" element={<F resource="notifications" title="Notifications" description="View your account notifications."/>}/><Route path="/customer/support" element={<F resource="support" title="Support" description="Create and track support requests."/>}/>
 </Route></Route>
 <Route element={<ProtectedRoute roles={["RIDER"]}/>}><Route element={<AppLayout/>}>
  <Route path="/rider/dashboard" element={<RiderDashboard/>}/><Route path="/rider/pickups" element={<RiderPickups/>}/><Route path="/rider/pickup-details" element={<F resource="pickups" title="Pickup Details" description="View assigned pickup details, customer information and location."/>}/><Route path="/rider/history" element={<F resource="pickups" title="History" description="View completed assigned pickups."/>}/><Route path="/rider/notifications" element={<F resource="notifications" title="Notifications" description="View rider notifications."/>}/><Route path="/rider/profile" element={<F resource="profiles" title="Profile" description="Manage your rider profile."/>}/>
 </Route></Route>
 <Route path="*" element={<Navigate to="/" replace/>}/>
 </Routes>}
